define(function(){
    if(typeof deconcept=="undefined")var deconcept={};if(typeof deconcept.util=="undefined")deconcept.util={};if(typeof deconcept.SWFObjectUtil=="undefined")deconcept.SWFObjectUtil={};
deconcept.SWFObject=function(a,b,c,d,e,f,g,h,i,j,k){if(document.createElement&&document.getElementById){this.DETECT_KEY=k?k:"detectflash";this.skipDetect=true;this.params={};this.variables={};this.attributes=[];a&&this.setAttribute("swf",a);b&&this.setAttribute("id",b);c&&this.setAttribute("width",c);d&&this.setAttribute("height",d);e&&this.setAttribute("version",new deconcept.PlayerVersion(e.toString().split(".")));this.installedVer=deconcept.SWFObjectUtil.getPlayerVersion(this.getAttribute("version"),
g);f?this.addParam("bgcolor",f):this.addParam("wmode","transparent");this.addParam("quality",h?h:"high");this.setAttribute("useExpressInstall",g);this.setAttribute("doExpressInstall",false);this.setAttribute("xiRedirectUrl",i?i:window.location);this.setAttribute("redirectUrl","");j&&this.setAttribute("redirectUrl",j)}};
deconcept.SWFObject.prototype={setAttribute:function(a,b){this.attributes[a]=b},getAttribute:function(a){return this.attributes[a]},addParam:function(a,b){this.params[a]=b},getParams:function(){return this.params},addVariable:function(a,b){this.variables[a]=b},getVariable:function(a){return this.variables[a]},getVariables:function(){return this.variables},getVariablePairs:function(){var a=[],b,c=this.getVariables();for(b in c)a.push(b+"="+c[b]);return a},getSWFHTML:function(){var a="";if(navigator.plugins&&
navigator.mimeTypes&&navigator.mimeTypes.length){this.getAttribute("doExpressInstall")&&this.addVariable("MMplayerType","PlugIn");a='<embed type="application/x-shockwave-flash" src="'+this.getAttribute("swf")+'" width="'+this.getAttribute("width")+'" height="'+this.getAttribute("height")+'"';a+=' id="'+this.getAttribute("id")+'" name="'+this.getAttribute("id")+'" ';var b=this.getParams(),c;for(c in b)a+=[c]+'="'+b[c]+'" ';c=this.getVariablePairs().join("&");if(c.length>0)a+='flashvars="'+c+'"';a+=
' pluginspage="http://www.macromedia.com/go/getflashplayer"/>'}else{this.getAttribute("doExpressInstall")&&this.addVariable("MMplayerType","ActiveX");a='<object id="'+this.getAttribute("id")+'" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="'+this.getAttribute("width")+'" height="'+this.getAttribute("height")+'" >';a+='<param name="movie" value="'+this.getAttribute("swf")+'" />';b=this.getParams();for(c in b)a+='<param name="'+c+'" value="'+b[c]+'" />';c=this.getVariablePairs().join("&");
if(c.length>0)a+='<param name="flashvars" value="'+c+'" />';a+="</object>"}return a},write:function(a){if(this.getAttribute("useExpressInstall"))if(this.installedVer.versionIsValid(new deconcept.PlayerVersion([6,0,65]))&&!this.installedVer.versionIsValid(this.getAttribute("version"))){this.setAttribute("doExpressInstall",true);this.addVariable("MMredirectURL",escape(this.getAttribute("xiRedirectUrl")));document.title=document.title.slice(0,47)+" - Flash Player Installation";this.addVariable("MMdoctitle",
document.title)}if(this.skipDetect||this.getAttribute("doExpressInstall")||this.installedVer.versionIsValid(this.getAttribute("version"))){(typeof a=="string"?document.getElementById(a):a).innerHTML=this.getSWFHTML();return true}else this.getAttribute("redirectUrl")!=""&&document.location.replace(this.getAttribute("redirectUrl"));return false}};
deconcept.SWFObjectUtil.getPlayerVersion=function(a,b){var c=new deconcept.PlayerVersion([0,0,0]);if(navigator.plugins&&navigator.mimeTypes.length){var d=navigator.plugins["Shockwave Flash"];if(d&&d.description)c=new deconcept.PlayerVersion(d.description.replace(/([a-z]|[A-Z]|\s)+/,"").replace(/(\s+r|\s+b[0-9]+)/,".").split("."))}else{try{d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");for(var e=15;e>6;e--)try{d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+e);c=new deconcept.PlayerVersion([e,
0,0]);break}catch(f){}}catch(g){}if(a&&c.major>a.major)return c;if(!a||(a.minor!=0||a.rev!=0)&&c.major==a.major||c.major!=6||b)try{c=new deconcept.PlayerVersion(d.GetVariable("$version").split(" ")[1].split(","))}catch(h){}}return c};deconcept.PlayerVersion=function(a){this.major=parseInt(a[0])!=null?parseInt(a[0]):0;this.minor=parseInt(a[1])||0;this.rev=parseInt(a[2])||0};
deconcept.PlayerVersion.prototype.versionIsValid=function(a){if(this.major<a.major)return false;if(this.major>a.major)return true;if(this.minor<a.minor)return false;if(this.minor>a.minor)return true;if(this.rev<a.rev)return false;return true};deconcept.util={getRequestParameter:function(a){var b=document.location.search||document.location.hash;if(b){a=b.indexOf(a+"=");var c=b.indexOf("&",a)>-1?b.indexOf("&",a):b.length;if(b.length>1&&a>-1)return b.substring(b.indexOf("=",a)+1,c)}return""}};
if(Array.prototype.push==null)Array.prototype.push=function(a){this[this.length]=a;return this.length};var getQueryParamValue=deconcept.util.getRequestParameter,FlashObject=deconcept.SWFObject,SWFObject=deconcept.SWFObject;
    return SWFObject;
})